services:
  - type: web
    name: habitflow
    runtime: python
    plan: free

    buildCommand: pip install --no-cache-dir -r requirements.txt

    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 2 --access-logfile - run:app

    healthCheckPath: /health

    envVars:
      - key: FLASK_ENV
        value: production

      - key: SECRET_KEY
        generateValue: true

      - key: DATABASE_URL
        fromDatabase:
          name: habitflow
          property: connectionString

databases:
  - name: habitflow
    databaseName: habitflow
    user: habitflow
    postgresMajorVersion: 16
    plan: free